### ISSUE TITLE
Uncompatible with IE

### ISSUE THREAD

**Issue by justanewbie00** [crazychicken/t-scroll#8] opened 2017-10-12 07:48 UTC
The animation is not working in IE when scrolled down. The element has style:  opacity : 0.

**Comment by 60late** [comment] 2018-03-15 07:46
I think you should abandon IE, it's totally obsoleted.

**Comment by seoMattH** [comment] 2018-05-01 14:47
I am having the same issue.  I would like to abandon IE altogether but that isn't possible.  Is it possible to make this work with IE11?  It looks like the issue is coming from the javascript.  Can it be re-written a little so the opacity shows up as 1 on IE?  The documentation of this project says  Internet Explorer 10+

**Comment by seoMattH** [comment] 2018-05-01 17:39
My solution isn't perfect, but it removes animation from IE and shows it on other browsers.  Add this to the top of your t-scroll.min.js script 

if(navigator.userAgent.indexOf('MSIE')!==-1
|| navigator.appVersion.indexOf('Trident/') > 0){
   /* Microsoft Internet Explorer detected in. */
}
else {

Then don't forget to add a closing bracket at the very end of the script to close the else tag

**Comment by crazychicken** [comment] 2018-07-13 05:09
I have updated t-scroll. Fix uncompatible with IE. You can try new version.
https://www.npmjs.com/package/t-scroll

**Closed as completed by crazychicken** 2018-07-13 05:09 UTC
